In [25]:
import pandas as pd

# Ações

In [26]:
df_acoes = pd.read_csv("fundamentus_acoes.csv")

In [27]:
df_acoes.head()

,Papel,Cotacao,PL,PVP,PSR,DY,PAtivo,PCapGiro,PEBIT,PAtivCircLiq,...,EVEBITDA,MargEBIT,MargLiq,LiqCorr,ROIC,ROE,Liq2meses,PatrimLiquido,DivBrutaPatrim,CrescRec5a
0,PMET3,"0,00","0,00","0,00","0,000","0,00%","0,000","0,00","0,00","0,00",...,"0,00","0,00%","0,00%","0,00","0,00%","4,10%","0,00","-290.863.000,00","0,00","37,74%"
1,MNSA3,"0,42","0,00","0,00","0,000","0,00%","0,000","0,00","0,00","0,00",...,"0,00","-208,15%","-362,66%","3,63","-13,50%","145,70%","0,00","-9.105.000,00","-6,52","-41,11%"
2,MNSA4,"0,47","0,00","0,00","0,000","0,00%","0,000","0,00","0,00","0,00",...,"0,00","-208,15%","-362,66%","3,63","-13,50%","145,70%","0,00","-9.105.000,00","-6,52","-41,11%"
3,IVTT3,"0,00","0,00","0,00","0,000","0,00%","0,000","0,00","0,00","0,00",...,"0,00","0,00%","0,00%","0,00","0,00%","-0,40%","0,00","1.083.050.000,00","0,00","20,67%"
4,CSTB4,"147,69","0,00","0,00","0,000","0,00%","0,000","0,00","0,00","0,00",...,"0,00","40,85%","28,98%","2,60","22,40%","20,11%","0,00","8.420.670.000,00","0,14","31,91%"

In [28]:
df_acoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Papel           997 non-null    str
 1   Cotacao         997 non-null    str
 2   PL              997 non-null    str
 3   PVP             997 non-null    str
 4   PSR             997 non-null    str
 5   DY              997 non-null    str
 6   PAtivo          997 non-null    str
 7   PCapGiro        997 non-null    str
 8   PEBIT           997 non-null    str
 9   PAtivCircLiq    997 non-null    str
 10  EVEBIT          997 non-null    str
 11  EVEBITDA        997 non-null    str
 12  MargEBIT        997 non-null    str
 13  MargLiq         997 non-null    str
 14  LiqCorr         997 non-null    str
 15  ROIC            997 non-null    str
 16  ROE             997 non-null    str
 17  Liq2meses       997 non-null    str
 18  PatrimLiquido   997 non-null    str
 19  DivBrutaPatrim  997 non-null    str
 20  CrescRec5a      997 non-null    str
dtypes: str(21)
memory usage: 163.7 KB

In [29]:
colunas_percent = [
    "DY","MargEBIT","MargLiq","ROIC","ROE","CrescRec5a"
]

colunas_numericas = [
    "Cotacao","PL","PVP","PSR","PAtivo","PCapGiro","PEBIT",
    "PAtivCircLiq","EVEBIT","EVEBITDA","LiqCorr",
    "Liq2meses","PatrimLiquido","DivBrutaPatrim"
]


for col in colunas_percent:
    df_acoes[col] = (
        df_acoes[col]
        .str.replace("%", "", regex=False)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    ) / 100

for col in colunas_numericas:
    df_acoes[col] = (
        df_acoes[col]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

In [30]:
df_acoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Papel           997 non-null    str
 1   Cotacao         997 non-null    float64
 2   PL              997 non-null    float64
 3   PVP             997 non-null    float64
 4   PSR             997 non-null    float64
 5   DY              997 non-null    float64
 6   PAtivo          997 non-null    float64
 7   PCapGiro        997 non-null    float64
 8   PEBIT           997 non-null    float64
 9   PAtivCircLiq    997 non-null    float64
 10  EVEBIT          997 non-null    float64
 11  EVEBITDA        997 non-null    float64
 12  MargEBIT        997 non-null    float64
 13  MargLiq         997 non-null    float64
 14  LiqCorr         997 non-null    float64
 15  ROIC            997 non-null    float64
 16  ROE             997 non-null    float64
 17  Liq2meses       997 non-null    float64
 18  PatrimLiquido   997 non-null    float64
 19  DivBrutaPatrim  997 non-null    float64
 20  CrescRec5a      997 non-null    float64
dtypes: float64(20), str(1)
memory usage: 163.7 KB

# FIIs

In [31]:
df_fii = pd.read_csv("fundamentus_fii.csv")

In [32]:
df_fii.head()

,Papel,Segmento,Cotacao,FFO_Yield,Dividend_Yield,PVP,Valor_de_Mercado,Liquidez,Qtd_de_Imoveis,Preco_m2,Aluguel_m2,Cap_Rate,Vacancia_Media
0,AAZQ11,Outros,"7,99","13,11%","7,02%","0,92",192.058.000,679.849,0,"0,00","0,00","0,00%","0,00%"
1,ABCP11,Shoppings,"79,80","9,56%","9,69%","0,72",375.785.000,71.903,1,"5.242,97","634,43","12,10%","1,22%"
2,AEFI11,Outros,"174,90","8,55%","0,00%","1,75",411.893.000,0,0,"0,00","0,00","0,00%","0,00%"
3,AERO11,Logística,"100,01","0,00%","0,00%","1,01",62.732.400,470.210,0,"0,00","0,00","0,00%","0,00%"
4,AFCR11,Multicategoria,"103,15","12,61%","0,00%","1,07",498.867.000,0,0,"0,00","0,00","0,00%","0,00%"

In [33]:
df_fii.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Papel             552 non-null    str
 1   Segmento          552 non-null    str
 2   Cotacao           552 non-null    str
 3   FFO_Yield         552 non-null    str
 4   Dividend_Yield    552 non-null    str
 5   PVP               552 non-null    str
 6   Valor_de_Mercado  552 non-null    str
 7   Liquidez          552 non-null    str
 8   Qtd_de_Imoveis    552 non-null    int64
 9   Preco_m2          552 non-null    str
 10  Aluguel_m2        552 non-null    str
 11  Cap_Rate          552 non-null    str
 12  Vacancia_Media    552 non-null    str
dtypes: int64(1), str(12)
memory usage: 56.2 KB

In [34]:
# colunas com porcentagem
colunas_percent = [
    "FFO_Yield",
    "Dividend_Yield",
    "Cap_Rate",
    "Vacancia_Media"
]

# colunas numéricas
colunas_numericas = [
    "Cotacao",
    "PVP",
    "Valor_de_Mercado",
    "Liquidez",
    "Preco_m2",
    "Aluguel_m2"
]

# tratar porcentagens
for col in colunas_percent:
    df_fii[col] = (
        df_fii[col]
        .str.replace("%", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    ) / 100

# tratar números
for col in colunas_numericas:
    df_fii[col] = (
        df_fii[col]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

In [35]:
df_fii.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Papel             552 non-null    str
 1   Segmento          552 non-null    str
 2   Cotacao           552 non-null    float64
 3   FFO_Yield         552 non-null    float64
 4   Dividend_Yield    552 non-null    float64
 5   PVP               552 non-null    float64
 6   Valor_de_Mercado  552 non-null    float64
 7   Liquidez          552 non-null    float64
 8   Qtd_de_Imoveis    552 non-null    int64
 9   Preco_m2          552 non-null    float64
 10  Aluguel_m2        552 non-null    float64
 11  Cap_Rate          552 non-null    float64
 12  Vacancia_Media    552 non-null    float64
dtypes: float64(10), int64(1), str(2)
memory usage: 56.2 KB

In [37]:
import os

# O 'r' antes das aspas resolve o problema das barras
diretorio = r"C:\Users\gabrielleite\Desktop\fiap-aws"

if not os.path.exists(diretorio):
    os.makedirs(diretorio)
    print(f"Pasta '{diretorio}' criada!")

# Usando f-string com o caminho corrigido
df_acoes.to_csv(os.path.join(diretorio, "clean_acoes.csv"), index=False, encoding='utf-8-sig', sep=';')
df_fii.to_csv(os.path.join(diretorio, "clean_fii.csv"), index=False, encoding='utf-8-sig', sep=';')

print("Arquivos salvos com sucesso!")

Arquivos salvos com sucesso!